namespace: zjleblanc
name: kasa
version: 1.0.6

authors:
- Zach LeBlanc <zjleblanc3@gmail.com>
description: Kasa Smart Device Home Automation
readme: README.md

license_file: LICENSE

tags:
  - kasa
  - smart_device
  - home_automation

repository: https://github.com/zjleblanc/zjleblanc.kasa
documentation: https://github.com/zjleblanc/zjleblanc.kasa/blob/master/README.md
homepage: https://github.com/zjleblanc/zjleblanc.kasa
issues: https://github.com/zjleblanc/zjleblanc.kasa/issues

dependencies: {}
build_ignore:
  - .venv
  - .gitignore

