---
- name: Manage Kasa devices
  hosts: "{{ bastion }}"
  gather_facts: false

  tasks:
    - name: Assert target devices defined
      ansible.builtin.assert:
        that: kasa_devices is defined

    - name: Discover devices on network
      zjleblanc.kasa.discover:
      register: r_discovery

    - name: Manage devices
      block:
        - name: "Set smart device | {{ desired_state_desc[desired_state] }}"
          loop: "{{ kasa_devices }}"
          loop_control:
            loop_var: device
            label: "{{ device.name }}-{{ device.state }}"
          register: r_managed_devices
          zjleblanc.kasa.smart_device:
            # see filter plugin in ../plugins/filter/kasa.py
            target: "{{ r_discovery.smart_devices | zjleblanc.kasa.kasa_host(device.name) }}"
            state: "{{ device.state }}"

        - name: Display device state(s)
          ansible.builtin.debug:
            var: r_managed_devices
      rescue:
        - name: Fail gracefully
          ansible.builtin.debug:
            msg: "Failed to manage regular devices"
